# -*- coding: utf-8 -*-
"""Copy of 13 - Žinių užtvirtinimas 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfMNyrK9T_m1RJ5nexLB94K6zwhvgHEe

# Žinių užtvirtinimas (1)

## Užduoties tikslas

Suskaičiuoti kiek duonos kepalų kepykla sugebės iškepti per dieną, ar spės įgyvendinti visus dienos užsakymus ir suskaičiuoti kiek iš jų uždirbs pelno.

## Duomenys

Apibrėžti duomenys:

- Darbo valandų per dieną - 8 val.

Jūsų suvedami duomenys:

- Kiek darbuotojas gali iškepti kepalų per valandą.
- Kiek darbuotojų turi kepykla.
- Vieno kepalo savikaina.
- Vieno kepalo pardavimo kaina.
- Kiek kepykla turi tą dieną iškepti kepalų (užsakymai).
"""

#Kiek darbuotojas gali iškepti kepalų per valandą.
vienas_darb_per_h = 20
#Kiek darbuotojų turi kepykla.
darbuotoju_kiekis = 3
#Vieno kepalo savikaina.
kepalo_savikaina = 1
#Vieno kepalo pardavimo kaina.
pardavimo_kaina = 2.50
#Kiek kepykla turi tą dieną iškepti kepalų (užsakymai).
uzsakymas = 300

"""## Skaičiavimai

Suskaičiuoti kiek kepykla per vieną darbo dieną spės iškepti duonos kepalų.
"""

kepalu_per_diena = 8 * vienas_darb_per_h * darbuotoju_kiekis
print(f'Per dieną iškepamų kepalų kiekis:{kepalu_per_diena} vnt.'  )

"""Apskaičiuoti visų kepalų savikainą, gautas pajamas pardavus ir iš to gauto pelno dalį."""

visu_kepalu_savikaina = kepalu_per_diena * kepalo_savikaina
print(f'Visų kepalų savikaina: {visu_kepalu_savikaina} Eur.')
print()
gautos_pajamos_pardavus = kepalu_per_diena * pardavimo_kaina
print(f'Gautos pajamos pardavus: {gautos_pajamos_pardavus} Eur.')
print()
pelnas = gautos_pajamos_pardavus - visu_kepalu_savikaina
print(f'Pelnas: {pelnas} Eur.')

"""Patikrinti ar kepykla spės iškepti visus tos dienos užsakymus. Jei ne, suskaičiuoti kiek kepalų nespės iškepti."""

if uzsakymas <= kepalu_per_diena:
    print('Spės iškepti')
else:
    print('Nespės iškepti')

"""(Papildomai) Įvertinkite tai, kad pajamas ir pelną galite gauti tik iš parduotų kepalų."""

realus_pelnas = uzsakymas * pardavimo_kaina - visu_kepalu_savikaina
print(f'Realus pelnas: {realus_pelnas} Eur.')