# -*- coding: utf-8 -*-
"""Python atsiskaitymas Orinta Pociūnienė.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkQKbOcnI7AYPBmA4xcWqmOrc_BVJFv2
"""

import pandas as pd
duomenys = pd.read_excel('Sakila_films_customers.xlsx')
duomenys

# Už kiek pigiausiai galima išsinuomuoti filmą?
duomenys['full_price'].min()

# Už kiek brangiausiai galima išsinuomuoti filmą?
duomenys['full_price'].max()

# Kiek iš viso nuomuojama filmų?
duomenys['film_id'].max()

# Iš kurių filmų buvo daugiausia ir mažiausia pajamų?
duomenys.groupby('title').sum()['full_price'].sort_values(ascending=False)

# Kurie vartotojas daugiausiai ir kurie mažiausiai išleido filmų nuomai?
duomenys.groupby('Customer').sum()['full_price'].sort_values(ascending=False)

# Kokių skirtingų kategorijų filmai būna?
kategoriju_pavadinimai = duomenys['category_name'].unique()
print(kategoriju_pavadinimai)

# Kokios kategorijos filmai buvo patys populiariausi?
import pandas as pd
import matplotlib.pyplot as plt
duomenys = pd.read_excel('Sakila_films_customers.xlsx')
filmu_skaicius = duomenys['category_name'].value_counts()     #Kiek filmu tenka kiekvienai kategorijai

kategorijos = filmu_skaicius.index
filmu_kiekiai = filmu_skaicius.values

plt.bar(kategorijos, filmu_kiekiai)                          # stulpeline diagrama
plt.xlabel('Kategorija')                                     # X asis
plt.ylabel('Išnuomotų filmų skaičius')                       # Y asis
plt.title('Išnuomotų filmų skaičius pagal kategoriją')       #diagramos pavadinimas
plt.xticks(rotation=45)                                      #lengviau skaitosi kategoriju pavadinimai
plt.show()