# -*- coding: utf-8 -*-

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/101laMe5HL-FMW26VoPpFzqtGPRybs6NK



### Užduotis 1

Leiskite vartotojui įvesti savo vardą. Ciklą `for` vykdykite tiek kartų kiek tame varde yra raidžių. Visais atvejais išveskite tą patį pasisveikinimą, pavyzdžiui "Labas, Ieva" (ši eilutė kartotųsi 4 kartus, kadangi varde "Ieva" yra 4 raidės).
"""

vardas = input('Įveskite savo vardą: ')
for _ in range(len(vardas)):
    # _ zenklu ignoruojama kintamojo reiksme, len yra lenght (ilgis)
    print("Labas, " + vardas)

"""### Užduotis 2

Susikurkite tokį ciklą: `for elementas in [88, 65, 21, 26, 47]`

Iš duotų skaičių išveskite visus skaičius, kurie yra lyginiai.
"""

for elementas in [88, 65, 21, 26, 47]:
    if elementas % 2 == 0:
        print (elementas)

"""### Užduotis 3

Leiskite vartotojui nurodyti rėžių pradžią, pabaigą, žingsnį. Taip pat, kokius skaičius jis nori matyti (lyginius ar nelyginius). Patikrinkite ar rėžiai tinkami, jei taip vykdykite ciklą, kuris eitų per nurodytą rėžių, darant atitinkamą žingsnį. Išveskite tik tokius skaičius kokius vartotojas pasirinko (lyginius arba nelyginius).
"""

pradzia = int(input("Įveskite rėžių pradžią: "))
pabaiga = int(input("Įveskite rėžių pabaigą: "))
zingsnis = int(input("Įveskite žingsnį (skaičių): "))
skaiciai = input("Ar norite matyti lyginius skaičius? (lyginiai/nelyginiai): ")

for skaicius in range(pradzia, pabaiga, zingsnis):
    if skaiciai.lower() == "lyginiai" and skaicius % 2 == 0:#lower, nes jei suves didziuju raidziu - nesuveiks
        print(skaicius)
    elif skaiciai.lower() == "nelyginiai" and skaicius % 2 != 0:
        print(skaicius)

"""### Užduotis 4

Su `for` pagalba, pamėginkite išvesti tokią eglutę:

```
*
**
***
****
*****
```

(papildomai) leiskite vartotojui pasirinkti kokio dydžio eglutė turėtų būti išvesta.
"""

eiluciu_skaicius = int(input("Kokio dydžio eglutės norėtumėte?(skaičius)"))
for dydis in range(1, eiluciu_skaicius + 1):# pradedam nuo virsaus, 1 *, o pabaiga eiluciu skaicius + 1, nes turi ieiti ir suvestas skaicius
    print("*" * dydis)

"""### Užduotis 5

Leiskite vartotojui įvesti bet kokį žodį, bei pasirinkti po kiek kartų turėtų būti pakartojama kiekviena raidė. Su ciklo pagalba išveskite kiekvieną raidę iš žodžio atskiroje eilutėje, taip pat, tą raidę eilutėje kartokite tiek kartų kiek pasirinko vartotojas.
"""

# Kaip pagrindą galite naudoti šį ciklą ir jį pakeisti:
# tekstas = 'obelis'
# for raide in tekstas:
#     print(raide * 10)


tekstas = input("Įveskite bet kokį žodį: ")
kartojimas = int(input("Įveskite, po kiek kartų turėtų būti pakartojama kiekviena raidė: "))

for raide in tekstas:
    print(raide * kartojimas)

"""### Užduotis 6

(papildomai, sunkiau) Be daugybos veiksmo programoje, sudauginkite du skaičius.
"""

a = 5
b = 3
# skaicius a bus pakartotas tiek ciklu kiek yra skaiciaus b reiksme,ignoruojant kintamojo reiksme (_) o sum visus pakartojimus sudes
sandauga = sum(a for _ in range (b))
print(sandauga)

"""### Užduotis 7

Susikurkite skaičiaus kintamąjį. Suraskite ar šis skaičius yra pirminis.
"""

# Pirminis skaičius – bet kuris natūralusis skaičius, didesnis nei 1,(nuo 2),
# kuris dalinasi tik iš savęs ir vieneto

skaicius = 30
if skaicius == 1:
    print(skaicius, "Nėra pirminis")
elif skaicius > 1:
   #tikrinam
   for i in range(2,skaicius):
       if (skaicius % i) == 0:
           print(skaicius,"Nėra pirminis")
           break
   else:
       print(skaicius,"Yra pirminis")
# jei skaičius yra mažiau ar lygu 1
# tai nėra pirminis
else:
   print(skaicius,"Nėra pirminis")